- name: Install Go via mise
  shell: ~/.local/bin/mise use --global go@latest
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.local/bin:{{ ansible_facts['env']['PATH'] }}"
  tags:
    - install
    - golang
