- name: Add Go PPA
  apt_repository:
    repo: ppa:longsleep/golang-backports
    state: present
    tags:
      - golang
- name: Update apt cache
  apt:
    update_cache: yes
    tags:
      - golang
- name: Install golang-go
  apt:
    name: golang-go
    state: present
    tags:
      - golang
