- name: Install Node.js LTS via mise
  shell: ~/.local/bin/mise use --global node@lts
  tags:
    - install
    - node

- name: Setup npm global prefix
  shell: |
    mkdir -p ~/.local/.npm-global
    eval "$(~/.local/bin/mise activate bash)"
    npm config set prefix '~/.local/.npm-global'
  args:
    executable: /bin/bash
  tags:
    - install
    - node
