- name: Install Yarn
  npm:
    name: yarn
    global: yes
    executable: ~/.local/bin/mise exec -- npm
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.local/bin:{{ ansible_facts['env']['PATH'] }}"
  tags:
    - install
    - node
- name: Install eslint
  npm:
    name: eslint
    global: yes
    executable: ~/.local/bin/mise exec -- npm
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.local/bin:{{ ansible_facts['env']['PATH'] }}"
  tags:
    - install
    - node
- name: Install Typescript server
  npm:
    name: typescript-language-server
    global: yes
    executable: ~/.local/bin/mise exec -- npm
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.local/bin:{{ ansible_facts['env']['PATH'] }}"
  tags:
    - install
    - node
- name: Install Typescript
  npm:
    name: typescript
    global: yes
    executable: ~/.local/bin/mise exec -- npm
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.local/bin:{{ ansible_facts['env']['PATH'] }}"
  tags:
    - install
    - node
- name: Install TS-Node
  npm:
    name: ts-node
    global: yes
    executable: ~/.local/bin/mise exec -- npm
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.local/bin:{{ ansible_facts['env']['PATH'] }}"
  tags:
    - install
    - node
- name: Install Prettierd
  npm:
    name: "@fsouza/prettierd"
    global: yes
    executable: ~/.local/bin/mise exec -- npm
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.local/bin:{{ ansible_facts['env']['PATH'] }}"
  tags:
    - install
    - node
